#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/config/.kodi/userdata \
	/var/cache/samba

# copy configs
[[ ! -e /config/.kodi/userdata/advancedsettings.xml ]] && \
	cp /defaults/advancedsettings.xml /config/.kodi/userdata/advancedsettings.xml

if [ -n "$MYSQL_HOST" ]; then
	sed -i -E "s/<host>.*?<\/host>/<host>$MYSQL_HOST<\/host>/g" /config/.kodi/userdata/advancedsettings.xml
fi

if [ -n "$MYSQL_PORT" ]; then
	sed -i -E "s/<port>.*?<\/port>/<port>$MYSQL_PORT<\/port>/g" /config/.kodi/userdata/advancedsettings.xml
fi

if [ -n "$MYSQL_USER" ]; then
	sed -i -E "s/<user>.*?<\/user>/<user>$MYSQL_USER<\/user>/g" /config/.kodi/userdata/advancedsettings.xml
fi

if [ -n "$MYSQL_PASSWORD" ]; then
	sed -i -E "s/<pass>.*?<\/pass>/<pass>$MYSQL_PASSWORD<\/pass>/g" /config/.kodi/userdata/advancedsettings.xml
fi

if [ -n "$TZ" ]; then
	echo "Setting timezone to ${TZ}..."
	ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime
	echo ${TZ} > /etc/timezone
fi
#make cron job for auto updates
[[ ! -e /mnt/con.conf ]] && \
	cp /config/.kodi/cron.conf /mnt/cron.conf
	cp /config/.kodi/update.sh /mnt/update.sh
	cp /config/.kodi/clean.sh /mnt/clean.sh
chmod 600 /mnt/cron.conf
chmod +x /mnt/clean.sh
chmod +x /mnt/update.sh
crontab /mnt/cron.conf

#copycron services run
mkdir /etc/services.d/cron
cp /config/.kodi/run.conf /etc/services.d/cron/run
chmod +x /etc/services.d/cron/run
# permissions
lsiown -R abc:abc \
	/config \
	/var/cache/samba
