name: coolasice1999/kodi-headless-20
run-name: ${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  build_amd64:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: hub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: build
      uses: docker/build-push-action@v2
      with:
        context: .
        pull: true
        push: true
        platforms: linux/amd64
        tags: coolasice1999/kodi-headless-v20:${{ github.ref_name }}-latest
